### ISSUE TITLE
Error 500 on explorer

### ISSUE THREAD

**Issue by josx** [fullcube/loopback-ds-paginate-mixin#3]
Just download and try it to use it!
I am using mongo and have and empty model, go to explorer and try it out.
Response error:

```
{
  "error": {
    "name": "TypeError",
    "status": 500,
    "message": "Cannot call method 'then' of undefined",
    "stack": "TypeError: Cannot call method 'then' of undefined\n    at Function.Paginate.Model.paginate (/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback-ds-paginate-mixin/index.js:120:23)\n    at SharedMethod.invoke (/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:234:25)\n    at HttpContext.invoke (/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:375:12)\n    at /home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:608:11\n    at execStack (/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:448:7)\n    at /home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback/lib/application.js:326:13\n    at /home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback/lib/model.js:295:5\n    at /home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback/common/models/acl.js:437:23\n    at /home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/async/lib/async.js:254:17\n    at async.each (/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/async/lib/async.js:121:20)"
  }
}
```

Also on server console have another error:

```
/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
TypeError: object is not a function
    at allCb (/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback-datasource-juggler/lib/dao.js:910:7)
    at /home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback-connector-mongodb/lib/mongodb.js:597:7
    at handleCallback (/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:95:12)
    at /home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/cursor.js:688:16
    at handleCallback (/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:248:5)
    at setCursorNotified (/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:457:3)
    at /home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:560:16
    at queryCallback (/home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:224:5)
    at /home/josx/Desarrollo/crear/proyectos/DealsAndReviews/node_modules/loopback/node_modules/continuation-local-storage/context.js:74:17
    at b (domain.js:183:18)
```

Any clue to solve this?

**Comment by josx** [comment]
Update on loopback-datasource-juggler fix this issue:

On my package.json

```
-    "loopback-datasource-juggler": "2.16.0",
+    "loopback-datasource-juggler": "2.36.0",
```
